# Generated by Django 4.2 on 2023-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_categoria_imagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.ImageField(blank=True, upload_to='categoria/<int:pk>/'),
        ),
    ]
