# Generated by Django 4.2 on 2023-08-31 18:11

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_categoria_imagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.ImageField(blank=True, upload_to=backend.models.up_imagem_categoria),
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pdf', models.CharField(max_length=100)),
                ('descricao_pdf', models.TextField()),
                ('categoria_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoria')),
            ],
        ),
    ]
