# Generated by Django 4.2 on 2023-08-31 18:18

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_categoria_imagem_categoria_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='pdf_file',
            field=models.ImageField(blank=True, upload_to=backend.models.up_pdf),
        ),
    ]
