# Generated by Django 4.2 on 2023-10-04 22:56

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_manual_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=backend.models.up_pdf),
        ),
    ]
